import UIKit

struct ColorManager {
    static let common_0 = UIColor(named: "Common_0")
    static let common_100 = UIColor(named: "Common_100")
    
    static let gray_5 = UIColor(named: "Gray_5")
    static let gray_10 = UIColor(named: "Gray_10")
    static let gray_15 = UIColor(named: "Gray_15")
    static let gray_20 = UIColor(named: "Gray_20")
    static let gray_22 = UIColor(named: "Gray_22")
    static let gray_30 = UIColor(named: "Gray_30")
    static let gray_40 = UIColor(named: "Gray_40")
    static let gray_50 = UIColor(named: "Gray_50")
    static let gray_60 = UIColor(named: "Gray_60")
    static let gray_70 = UIColor(named: "Gray_70")
    static let gray_80 = UIColor(named: "Gray_80")
    static let gray_90 = UIColor(named: "Gray_90")
    static let gray_95 = UIColor(named: "Gray_95")
    static let gray_96 = UIColor(named: "Gray_96")
    static let gray_97 = UIColor(named: "Gray_97")
    static let gray_98 = UIColor(named: "Gray_98")
    static let gray_99 = UIColor(named: "Gray_99")
    
    static let orange_10 = UIColor(named: "Orange_10")
    static let orange_20 = UIColor(named: "Orange_20")
    static let orange_30 = UIColor(named: "Orange_30")
    static let orange_40 = UIColor(named: "Orange_40")
    static let orange_50 = UIColor(named: "Orange_50")
    static let orange_60 = UIColor(named: "Orange_60")
    static let orange_70 = UIColor(named: "Orange_70")
    static let orange_80 = UIColor(named: "Orange_80")
    static let orange_90 = UIColor(named: "Orange_90")
    static let orange_95 = UIColor(named: "Orange_95")
    static let orange_99 = UIColor(named: "Orange_99")

    static let red_10 = UIColor(named: "Red_10")
    static let red_20 = UIColor(named: "Red_20")
    static let red_30 = UIColor(named: "Red_30")
    static let red_40 = UIColor(named: "Red_40")
    static let red_50 = UIColor(named: "Red_50")
    static let red_60 = UIColor(named: "Red_60")
    static let red_70 = UIColor(named: "Red_70")
    static let red_80 = UIColor(named: "Red_80")
    static let red_90 = UIColor(named: "Red_90")
    static let red_95 = UIColor(named: "Red_95")
    static let red_99 = UIColor(named: "Red_99")

    static let yellow_70 = UIColor(named: "Yellow_70")
}
