import UIKit

struct ImageManager {
    //sns
    static let kakao = UIImage(named: "kakao")
    static let apple = UIImage(named: "apple")
    //direction
    static let arrow_Chevron_Left = UIImage(named: "Arrow_Chevron_Left")
    static let arrow_Chevron_Right = UIImage(named: "Arrow_Chevron_Right")
    static let chevron_Down = UIImage(named: "Chevron_Down")
    static let arrow_Left_Right = UIImage(named: "Arrow_Left_Right")
    static let arrow_Down = UIImage(named: "Arrow_Down")
    static let arrow_Right = UIImage(named: "Arrow_Right")
    static let chevron_Up = UIImage(named: "Chevron_Up")
    //tabbar
    static let home = UIImage(named: "home")
    static let alarm = UIImage(named: "alarm")
    static let setting = UIImage(named: "setting")
    static let home_Select = UIImage(named: "home_Select")
    static let alarm_Select = UIImage(named: "alarm_Select")
    static let setting_Select = UIImage(named: "setting_Select")
    //market
    static let binance = UIImage(named: "Binance")
    static let bybit = UIImage(named: "Bybit")
    static let upbit = UIImage(named: "Upbit")
    static let bithumb = UIImage(named: "Bithumb")
    //check
    static let check_Yellow = UIImage(named: "Check_Yellow")
    static let circle_Check = UIImage(named: "Circle_Check")
    static let circle_Check_Orange = UIImage(named: "Circle_Check_Orange")
    static let circle_Check_Green = UIImage(named: "Circle_Check_Green")
    static let check24 = UIImage(named: "Check24")
    static let check20 = UIImage(named: "Check20")
    static let check_Orange = UIImage(named: "Check_Orange")
    static let square_Check_None = UIImage(named: "Square_Check_None")
    static let square_Check_Select = UIImage(named: "Square_Check_Select")
    //sort
    static let sort = UIImage(named: "sort")
    static let sort_ascending = UIImage(named: "sort_ascending")
    static let sort_descending = UIImage(named: "sort_descending")
    //loginType
    static let login_kakao = UIImage(named: "login_kakao")
    static let login_apple = UIImage(named: "login_apple")
    static let login_coinmon = UIImage(named: "login_coinmon")
    //else
    static let loginCoinMon = UIImage(named: "loginCoinMon")
    static let iconClear = UIImage(named: "iconClear")
    static let search = UIImage(named: "search")
    static let noneAlarm = UIImage(named: "noneAlarm")
    static let nosearch = UIImage(named: "nosearch")
    static let global = UIImage(named: "global")
    static let notification_select24 = UIImage(named: "notification_select24")
    static let notification24 = UIImage(named: "notification24")
    static let notification20 = UIImage(named: "notification20")
    static let caution = UIImage(named: "caution")
    static let change_up = UIImage(named: "change_up")
    static let change_down = UIImage(named: "change_down")
    static let icon_star = UIImage(named: "icon_star")
    static let icon_star_select = UIImage(named: "icon_star_select")
    static let icon_search24 = UIImage(named: "icon_search24")
    static let Handle24 = UIImage(named: "Handle24")
    static let Star50 = UIImage(named: "Star50")
    static let icon_questionMark18 = UIImage(named: "icon_questionMark18")
    static let icon_close14 = UIImage(named: "icon_close14")
    static let indicator1 = UIImage(named: "indicator1")
    static let indicator2 = UIImage(named: "indicator2")
    static let indicator3 = UIImage(named: "indicator3")
    static let icon_More_Vertical = UIImage(named: "icon_More_Vertical")
}
